/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QE3xBTVhg91
 */
import {Input} from "@/components/ui/input.tsx"
import {Button} from "@/components/ui/button.tsx"
import DemoPage from "./explore"

export function HomePage() {
    return (
        <div className="flex justify-center">
            <div className="flex flex-col min-h-[100dvh]">
                <main className="flex-1">
                    <section className="w-full py-6 md:py-12 lg:py-20 xl:py-24">
                        <div className="container flex flex-col items-center justify-center space-y-4 px-4 md:px-6">
                            <div className="text-center space-y-2">
                                <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
                                    Learn a new language with Lingua Connect
                                </h1>
                                <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                                    The most immersive language learning platform. Learn from native speakers. Practice
                                    with
                                    AI. Connect
                                    with the world.
                                </p>
                            </div>
                            <div className="mx-auto w-full max-w-sm space-y-2">
                                <form className="flex space-x-2">
                                    <Input className="max-w-lg flex-1" placeholder="Enter your email" type="email"/>
                                    <Button type="submit">Sign Up</Button>
                                </form>
                                <p className="text-xs text-gray-500 dark:text-gray-400">
                                    Sign up to get notified when we launch.
                                    <a className="underline underline-offset-2" href="#">
                                        Terms & Conditions
                                    </a>
                                </p>
                            </div>
                        </div>
                    </section>
                    <section className="w-full py-12 md:py-24 bg-gray-100 dark:bg-gray-800">
                        <div className="container grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10">
                            <div className="space-y-3">
                                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">Interactive
                                    Lessons</h2>
                                <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                                    Learn through games, videos, and quizzes. Our platform makes learning fun and
                                    engaging.
                                </p>
                            </div>
                            <img
                                alt="Image"
                                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
                                height="310"
                                src="/placeholder.svg"
                                width="550"
                            />
                        </div>
                    </section>
                    <section className="w-full py-12 md:py-24">
                        <div className="container grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10">
                            <div className="space-y-3">
                                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">
                                    Personalized Learning
                                </h2>
                                <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                                    Everyone learns differently. Our AI-powered platform adapts to your learning style.
                                </p>
                            </div>
                            <img
                                alt="Image"
                                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
                                height="310"
                                src="/placeholder.svg"
                                width="550"
                            />
                        </div>
                    </section>
                    <section className="w-full py-12 md:py-24 lg:py-32 border-t">
                        <div className="container grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10">
                            <div className="space-y-3">
                                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">Global
                                    Community</h2>
                                <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                                    Connect with learners from around the world. Practice your new language with native
                                    speakers.
                                </p>
                            </div>
                            <img
                                alt="Image"
                                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
                                height="310"
                                src="/placeholder.svg"
                                width="550"
                            />
                        </div>
                    </section>
                    <section className="w-full py-12 md:py-24 lg:py-32 border-t">
                        <div className="container grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10">
                            <div className="space-y-3">
                                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">Testimonials</h2>
                                <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                                    See what our users have to say about Lingua Connect.
                                </p>
                            </div>
                            <div className="mx-auto max-w-[800px] grid gap-6 lg:grid-cols-2 lg:gap-10">
                                <div className="space-y-4">
                                    <div
                                        className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                                        Interactive Lessons
                                    </div>
                                    <p className="text-gray-500 dark:text-gray-400">
                                        "I've tried other language learning apps, but Lingua Connect is the best. The
                                        lessons are fun and I
                                        feel like I'm really learning."
                                    </p>
                                    <strong className="font-medium">- Sarah, 25</strong>
                                </div>
                                <div className="space-y-4">
                                    <div
                                        className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                                        Personalized Learning
                                    </div>
                                    <p className="text-gray-500 dark:text-gray-400">
                                        "I've tried other language learning apps, but Lingua Connect is the best. The
                                        lessons are fun and I
                                        feel like I'm really learning."
                                    </p>
                                    <strong className="font-medium">- Sarah, 25</strong>
                                </div>
                            </div>
                        </div>
                    </section>
                    <section className="w-full py-12 md:py-24 lg:py-32 border-t">
                        <div className="container grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10">
                            <div className="space-y-3">
                                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">
                                    Ready to get started?
                                </h2>
                                <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                                    Sign up to get notified when we launch.
                                </p>
                            </div>
                            <div className="mx-auto w-full max-w-sm space-y-2">
                                <form className="flex space-x-2">
                                    <Input className="max-w-lg flex-1" placeholder="Enter your email" type="email"/>
                                    <Button type="submit">Sign Up</Button>
                                </form>
                            </div>
                        </div>
                    </section>
                </main>
            </div>

        </div>
    )
}